SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `feeds` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `url` text NOT NULL,
  `rate` int(11) NOT NULL,
  `frequency` enum('d','w','f','m','q','h','a') NOT NULL,
  `lastpulled` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;

CREATE TABLE IF NOT EXISTS `article` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `title` VARCHAR(100) NOT NULL, `images` TEXT, `videos` TEXT, `author` VARCHAR(100) NULL, `source` VARCHAR(100) NOT NULL, `extended` TEXT, `publish` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `keywords` TEXT,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `channel` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `description` TEXT, `sport` VARCHAR(50), `type` VARCHAR(50), `level` INT(1) NOT NULL default 1, `keywords` TEXT, `geolat` DECIMAL(10,6) default NULL, `geolng` DECIMAL(10,6) default NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `discussion` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `added` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `event` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `sport` VARCHAR(50), `type` VARCHAR(50), `keywords` TEXT, `participants` TEXT, `time` TEXT, `parent` INT(4) NULL, `location` TEXT, `geolat` DECIMAL(10,6) default NULL, `geolng` DECIMAL(10,6) default NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `user` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `name` VARCHAR(100), `email` VARCHAR(255) NOT NULL, `password` VARCHAR(50) NOT NULL, `facebook` VARCHAR(50) NULL, `twitter` VARCHAR(50) NULL, `google` VARCHAR(50) NULL, `linkedin` VARCHAR(50) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `follower` (
    `id` INT(11) NOT NULL AUTO_INCREMENT, `channel` INT(11) NOT NULL, `user` INT(11) NOT NULL, `added` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
