
CREATE USER 'unittest'@'localhost' IDENTIFIED BY  '***';
GRANT USAGE ON * . * TO  'unittest'@'localhost' IDENTIFIED BY  '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS  `unittest` ;
GRANT ALL PRIVILEGES ON  `unittest` . * TO  'unittest'@'localhost';
FLUSH PRIVILEGES;

use `unittest`;

